import { Inter } from 'next/font/google'
import './globals.css'
import Cabecalho from '../Components/Cabecalho/Cabecalho'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Porto Seguro and Fiap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="reset">
        <Cabecalho />
          {children}
      </body>
    </html>
  );
}
 